config/routes.rb
ChuckvoseRedesign2011Rails::Application.routes.draw do
  devise_for :users

  resources :content
  
  root :to => 'content#show'

end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  # # GET /content
  # # GET /content.xml
  # def index
  #   @content = Content.all
  # 
  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.xml  { render :xml => @content }
  #   end
  # end

  # GET /content/1
  # GET /content/1.xml
  def show
    params[:id] = 1 unless params[:id]
    
    @content = Content.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @content }
    end
  end
  # 
  # # GET /content/new
  # # GET /content/new.xml
  # def new
  #   @content = Content.new
  # 
  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.xml  { render :xml => @content }
  #   end
  # end
  # 
  # # GET /content/1/edit
  # def edit
  #   @content = Content.find(params[:id])
  # end
  # 
  # # POST /content
  # # POST /content.xml
  # def create
  #   @content = Content.new(params[:content])
  # 
  #   respond_to do |format|
  #     if @content.save
  #       format.html { redirect_to(@content, :notice => 'Content was successfully created.') }
  #       format.xml  { render :xml => @content, :status => :created, :location => @content }
  #     else
  #       format.html { render :action => "new" }
  #       format.xml  { render :xml => @content.errors, :status => :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # # PUT /content/1
  # # PUT /content/1.xml
  # def update
  #   @content = Content.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @content.update_attributes(params[:content])
  #       format.html { redirect_to(@content, :notice => 'Content was successfully updated.') }
  #       format.xml  { head :ok }
  #     else
  #       format.html { render :action => "edit" }
  #       format.xml  { render :xml => @content.errors, :status => :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # # DELETE /content/1
  # # DELETE /content/1.xml
  # def destroy
  #   @content = Content.find(params[:id])
  #   @content.destroy
  # 
  #   respond_to do |format|
  #     format.html { redirect_to(content_url) }
  #     format.xml  { head :ok }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/views/content/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/content/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', content_path %>

app/views/content/index.html.erb
<h1>Listing content</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @content.each do |content| %>
  <tr>
    <td><%= link_to 'Show', content %></td>
    <td><%= link_to 'Edit', edit_content_path(content) %></td>
    <td><%= link_to 'Destroy', content, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Content', new_content_path %>

app/views/content/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to 'Back', content_path %>

app/views/content/show.html.haml
%article
  %header
    %h1= @content.title
  %section
    =raw RedCloth.new(@content.description).to_html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChuckvoseRedesign2011Rails</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <link href='http://fonts.googleapis.com/css?family=Cardo' rel='stylesheet' type='text/css'>
</head>
<body>
  <section id="container">
    <header>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </header>
    <section id="content">
      <%= yield %>
    <section>
  </section>
</body>
</html>